name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Set environment variables
        run: echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> $GITHUB_ENV

      - name: Run tests
        run: flutter test

      - name: Build development APK
        run: flutter build apk --flavor development -t lib/main_development.dart

      - name: Upload development APK to Google Drive
        env:
          GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        run: |
          echo "$GDRIVE_SERVICE_ACCOUNT" > service_account.json
          curl -L https://raw.githubusercontent.com/prasmussen/gdrive/master/gdrive-linux-x64 -o gdrive
          chmod +x gdrive
          ./gdrive upload --service-account service_account.json --parent '1CzphxCRJLuoHqh-h_bVLPIq35tHF2YC0' --name app-development-release.apk build/app/outputs/flutter-apk/app-development-release.apk

      - name: Build production APK
        run: flutter build apk --flavor production -t lib/main_production.dart

      - name: Upload production APK to Google Drive
        env:
          GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        run: |
          echo "$GDRIVE_SERVICE_ACCOUNT" > service_account.json
          curl -L https://raw.githubusercontent.com/prasmussen/gdrive/master/gdrive-linux-x64 -o gdrive
          chmod +x gdrive
          ./gdrive upload --service-account service_account.json --parent '1CzphxCRJLuoHqh-h_bVLPIq35tHF2YC0' --name app-production-release.apk build/app/outputs/flutter-apk/app-production-release.apk
